### PR TITLE
Added YAPF Code Formatting

### PR DESCRIPTION
**Pull request by ismacaulay**
Added [`Yet Another Python Formatter`](https://github.com/google/yapf) along with a `pre-commit` hook to help ensure consistent styling. This will help contributors meet the repository's expected styling. It will be enforced in the travis build just like pylint. See @bsmithyman comment below for more info on styling.

### CODE REVIEW

**Comment by bsmithyman** [comment]
I haven't gone through line-by-line, but overall this looks pretty clean / consistent. I saw that you put some disables in there where needed – thanks for the extra effort @ismacaulay.

**Comment by bsmithyman** [comment]
To ensure consistent code style, we would like to use [`yapf`](https://github.com/google/yapf), which is an unofficial Google project; Yet Another Python Formatter. We use a custom style that closely replicates our target styling for Python source code.

```
[style]
based_on_style = pep8
dedent_closing_brackets = true
split_complex_comprehension = true
split_before_logical_operator = true
split_before_expression_after_opening_paren = true
split_before_first_argument = true
split_before_named_assigns = true
each_dict_entry_on_separate_line = true
continuation_align_style = fixed
continuation_indent_width = 4
column_limit: 79
allow_multiline_dictionary_keys = false
allow_split_before_dict_value = false
```

This style is written into a local `.style.yapf` file in the repository. To install the development requirement, add `yapf` to the `requirements_dev.txt` file. To install in your working environment, type `pip install yapf`. To run, type `yapf -rd ...` where `...` is the working directory (`-rd` means "recursive, show diffs"). The preceding is the correct call to use in CI tests. The `yapf` tool also works great with a variety of editor environments.

You can locally disable the formatter by surrounding a block of code in `# yapf: disable` ... `# yapf: enable` comments. Please use this selectively, and be prepared to review/reassess in the future if the enclosed code changes.

To automatically style code whenever you commit, create a file called `.pre-commit-config.yaml` in your repo with the following:

```yaml
repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    sha: 'bb280692bd3b1e1f7fab174635ef9678f2452522'
    hooks:
    -   id: yapf
```

Install with:
```bash
pip install pre-commit
pre-commit install
```

Now you will automatically get styled code when you commit.

**Comment by fwkoch** [comment]
Thanks @ismacaulay - I think we will hold off on this for now, though. I'm worried about discouraging contributions by requiring either strict style or an installed pre-commit hook. Also branches `properties` are held to somewhat strict pylint standards (but in light of this comment, I plan to start only enforcing pylint on deployed versions).

I tagged this work in case we decide to revisit: https://github.com/seequent/properties/tree/yapf-styling

**Comment by ismacaulay** [comment]
Those are fair concerns, and formatting can be revisited later if we so choose.

**Pull request closed without merging**
